
INSERT INTO role (nombre) VALUES ('ROLE_ADMINISTRADOR');
INSERT INTO role (nombre) VALUES ('ROLE_RECEPCIONISTA');
INSERT INTO role (nombre) VALUES ('ROLE_SERVICIOS');


INSERT INTO  tipos_de_documentos (nom_tipo_documento) VALUES ('REGISTRO CIVIL');
INSERT INTO  tipos_de_documentos (nom_tipo_documento) VALUES ('TARJETA DE IDENTIDAD');
INSERT INTO  tipos_de_documentos (nom_tipo_documento) VALUES ('CEDULA DE CIUDADANIA');

INSERT INTO  sexo (nom_sexo) VALUES ('O +');
INSERT INTO  sexo (nom_sexo) VALUES ('O  -');
INSERT INTO  sexo (nom_sexo) VALUES ('A +');
INSERT INTO  sexo (nom_sexo) VALUES ('A  -');


INSERT INTO database_sispart.role (nombre) VALUE('ROLE_ADMINISTRADOR');
INSERT INTO database_sispart.role (nombre) VALUE('ROLE_RECEPCIONISTA');

INSERT INTO database_sispart.tipos_de_sangre (nom_tipo_sangre) VALUES ('O+');
INSERT INTO database_sispart.tipos_de_sangre (nom_tipo_sangre) VALUES ('O-');
INSERT INTO database_sispart.tipos_de_sangre (nom_tipo_sangre) VALUES ('A+');
INSERT INTO database_sispart.tipos_de_sangre (nom_tipo_sangre) VALUES ('A-');

INSERT INTO `database_sispart`.`sexo` (`nom_sexo`) VALUES ('MASCULINO');
INSERT INTO `database_sispart`.`sexo` (`nom_sexo`) VALUES ('FEMENINO');


INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Afganistán');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Albania');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Alemania');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Andorra');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Angola');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('AntiguayBarbuda');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('ArabiaSaudita');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Argelia');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Argentina');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Armenia');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Aruba');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Australia');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Austria');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Azerbaiyán');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Bahamas');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Bangladé');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Barbados');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Baréin');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Bélgica');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Belice');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Benín');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Bielorrusia');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Birmania');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Bolivia');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('BosniayHerzegovina');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Botsuana');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Brasil');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Brunéi');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Bulgaria');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('BurkinaFaso');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Burundi');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Bután');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('CaboVerde');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Camboya');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Camerún');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Canadá');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Catar');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Chad');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Chile');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('China');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Chipre');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('CiudaddelVaticano');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Colombia');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Comoras');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('CoreadelNorte');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('CoreadelSur');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('CostadeMarfil');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('CostaRica');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Croacia');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Cuba');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Dinamarca','DANÉSA','DNK');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Dominica','DOMINIQUÉS','DMA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Ecuador','ECUATORIANA','ECU');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Egipto','EGIPCIA','EGY');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('ElSalvador','SALVADOREÑA','SLV');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('EmiratosÁrabesUnidos','EMIRATÍ','ARE');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Eritrea','ERITREA','ERI');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Eslovaquia','ESLOVACA','SVK');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Eslovenia','ESLOVENA','SVN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('España','ESPAÑOLA','ESP');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('EstadosUnidos','ESTADOUNIDENSE','USA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Estonia','ESTONIA','EST');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Etiopía','ETÍOPE','ETH');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Filipinas','FILIPINA','PHL');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Finlandia','FINLANDÉSA','FIN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Fiyi','FIYIANA','FJI');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Francia','FRANCÉSA','FRA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Gabón','GABONÉSA','GAB');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Gambia','GAMBIANA','GMB');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Georgia','GEORGIANA','GEO');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Gibraltar','GIBRALTAREÑA','GIB');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Ghana','GHANÉSA','GHA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Granada','GRANADINA','GRD');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Grecia','GRIEGA','GRC');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Groenlandia','GROENLANDÉSA','GRL');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Guatemala','GUATEMALTECA','GTM');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Guineaecuatorial','ECUATOGUINEANA','GNQ');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Guinea','GUINEANA','GIN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Guinea-Bisáu','GUINEANA','GNB');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Guyana','GUYANESA','GUY');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Haití','HAITIANA','HTI');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Honduras','HONDUREÑA','HND');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Hungría','HÚNGARA','HUN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('India','HINDÚ','IND');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Indonesia','INDONESIA','IDN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Irak','IRAQUÍ','IRQ');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Irán','IRANÍ','IRN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Irlanda','IRLANDÉSA','IRL');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Islandia','ISLANDÉSA','ISL');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('IslasCook','COOKIANA','COK');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('IslasMarshall','MARSHALÉSA','MHL');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('IslasSalomón','SALOMONENSE','SLB');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Israel','ISRAELÍ','ISR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Italia','ITALIANA','ITA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Jamaica','JAMAIQUINA','JAM');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Japón','JAPONÉSA','JPN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Jordania','JORDANA','JOR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Kazajistán','KAZAJA','KAZ');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Kenia','KENIATA','KEN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Kirguistán','KIRGUISA','KGZ');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Kiribati','KIRIBATIANA','KIR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Kuwait','KUWAITÍ','KWT');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Laos','LAOSIANA','LAO');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Lesoto','LESOTENSE','LSO');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Letonia','LETÓNA','LVA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Líbano','LIBANÉSA','LBN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Liberia','LIBERIANA','LBR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Libia','LIBIA','LBY');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Liechtenstein','LIECHTENSTEINIANA','LIE');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Lituania','LITUANA','LTU');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Luxemburgo','LUXEMBURGUÉSA','LUX');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Madagascar','MALGACHE','MDG');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Malasia','MALASIA','MYS');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Malaui','MALAUÍ','MWI');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Maldivas','MALDIVA','MDV');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Malí','MALIENSE','MLI');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Malta','MALTÉSA','MLT');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Marruecos','MARROQUÍ','MAR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Martinica','MARTINIQUÉS','MTQ');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Mauricio','MAURICIANA','MUS');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Mauritania','MAURITANA','MRT');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('México','MEXICANA','MEX');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Micronesia','MICRONESIA','FSM');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Moldavia','MOLDAVA','MDA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Mónaco','MONEGASCA','MCO');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Mongolia','MONGOLA','MNG');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Montenegro','MONTENEGRINA','MNE');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Mozambique','MOZAMBIQUEÑA','MOZ');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Namibia','NAMIBIA','NAM');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Nauru','NAURUANA','NRU');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Nepal','NEPALÍ','NPL');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Nicaragua','NICARAGÜENSE','NIC');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Níger','NIGERINA','NER');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Nigeria','NIGERIANA','NGA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Noruega','NORUEGA','NOR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('NuevaZelanda','NEOZELANDÉSA','NZL');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Omán','OMANÍ','OMN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('PaísesBajos','NEERLANDÉSA','NLD');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Pakistán','PAKISTANÍ','PAK');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Palaos','PALAUANA','PLW');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Palestina','PALESTINA','PSE');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Panamá','PANAMEÑA','PAN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('PapúaNuevaGuinea','PAPÚ','PNG');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Paraguay','PARAGUAYA','PRY');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Perú','PERUANA','PER');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Polonia','POLACA','POL');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Portugal','PORTUGUÉSA','PRT');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('PuertoRico','PUERTORRIQUEÑA','PRI');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('ReinoUnido','BRITÁNICA','GBR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('RepúblicaCentroafricana','CENTROAFRICANA','CAF');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('RepúblicaCheca','CHECA','CZE');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('RepúblicadeMacedonia','MACEDONIA','MKD');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('RepúblicadelCongo','CONGOLEÑA','COG');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('RepúblicaDemocráticadelCongo','CONGOLEÑA','COD');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('RepúblicaDominicana','DOMINICANA','DOM');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('RepúblicaSudafricana','SUDAFRICANA','ZAF');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Ruanda','RUANDÉSA','RWA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Rumanía','RUMANA','ROU');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Rusia','RUSA','RUS');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Samoa','SAMOANA','WSM');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('SanCristóbalyNieves','CRISTOBALEÑA','KNA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('SanMarino','SANMARINENSE','SMR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('SanVicenteylasGranadinas','SANVICENTINA','VCT');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('SantaLucía','SANTALUCENSE','LCA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('SantoToméyPríncipe','SANTOTOMENSE','STP');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Senegal','SENEGALÉSA','SEN');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Serbia','SERBIA','SRB');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Seychelles','SEYCHELLENSE','SYC');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('SierraLeona','SIERRALEONÉSA','SLE');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Singapur','SINGAPURENSE','SGP');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Siria','SIRIA','SYR');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Somalia','SOMALÍ','SOM');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('SriLanka','CEILANÉSA','LKA');
INSERT INTO`nacionalidad`(`PAIS_NAC`,`GENTILICIO_NAC`,`ISO_NAC`)VALUES('Suazilandia','SUAZI','SWZ');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('SudándelSur','SURSUDANÉSA','SSD');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Sudán','SUDANÉSA','SDN');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Suecia','SUECA','SWE');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Suiza','SUIZA','CHE');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Surinam','SURINAMESA','SUR');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Tailandia','TAILANDÉSA','THA');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Tanzania','TANZANA','TZA');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Tayikistán','TAYIKA','TJK');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('TimorOriental','TIMORENSE','TLS');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Togo','TOGOLÉSA','TGO');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Tonga','TONGANA','TON');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('TrinidadyTobago','TRINITENSE','TTO');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Túnez','TUNECINA','TUN');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Turkmenistán','TURCOMANA','TKM');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Turquía','TURCA','TUR');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Tuvalu','TUVALUANA','TUV');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Ucrania','UCRANIANA','UKR');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Uganda','UGANDÉSA','UGA');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Uruguay','URUGUAYA','URY');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Uzbekistán','UZBEKA','UZB');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Vanuatu','VANUATUENSE','VUT');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Venezuela','VENEZOLANA','VEN');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Vietnam','VIETNAMITA','VNM');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Yemen','YEMENÍ','YEM');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Yibuti','YIBUTIANA','DJI');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Zambia','ZAMBIANA','ZMB');
INSERT INTO database_sispart.nacionalidad (nombre) VALUES('Zimbabue','ZIMBABUENSE','ZWE');


INSERT INTO `database_sispart`.`empleados` (`apellido`, `arl`, `correo`, `direccion`, `edad`, `eps`, `fecha_nacimento`, `nom_contacto_emergencia`, `nombre`, `num_contacto_emergencia`, `num_documento`, `num_telefono`, `cod_sexo`, `tip_documento`, `tipo_sangre`) VALUES ('Maurico', 'SURA', 'die@unbosque.edu.co', 'calle100', '24', 'Compensar', '1999-06-14', 'Juan Mauricio', 'Diego', '3145678399', '1283920034', '324537489', '1', '3', '3');

INSERT INTO `database_sispart`.`huespedes` (`apellido`, `correo`, `estado_huesped`, `lugar_origen`, `nombre`, `num_celular`, `num_documento`, `cod_nacionalidad`, `cod_tip_documento`) VALUES ('Torres', 'sar@huesped.com', '1', 'Bogotá', 'Sara', '31456734987', '803673893', '43', '3');


